before:
  hooks:
    - go mod tidy    
builds:
  - id: epithet-oidc-plugin
    binary: epithet-oidc-plugin
    main: ./cmd/epithet-oidc-plugin/
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
  - id: epithet-oidc-policy
    binary: epithet-oidc-policy
    main: ./cmd/epithet-oidc-policy/
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: epithet-oidc
    github:
      owner: epithet-ssh
      name: homebrew-epithet
    commit_author:
      name: Epithet Bot
      email: bot@epithet.io
    folder: Formula
    caveats: "Installs the binaries, but no configs"    
    homepage: "https://epithet.io/"
    test: |
      system "#{bin}/epithet-oidc-plugin -h"
